### ISSUE TITLE
Adicionar Pacote de Extensões a extensão FriendsOfFlarum/gamification

### ISSUE THREAD

**Issue by GustavoLiima** [tiuram0n/brazilian-portuguese#3]
Não encontrei a tradução para a extensão "FriendsOfFlarum/gamification" na lista de pacotes. Há alguma previsão de adição? ou posso criar um pull request?

**Comment by tiuram0n** [comment]
Opa, pode criar sim! chegando em casa eu já adiciono.

**Comment by tiuram0n** [comment]
@GustavoLiima Tradução adicionada com sucesso.
Já adicionei uma nova versão.

Se já estiver com a extensão, basta usar o comando abaixo para atualizar:

`composer update`

**Comment by GustavoLiima** [comment]
Muito obrigado @tiuram0n 
Atualizei aqui, funcionou certinho

**Comment by tiuram0n** [comment]
@GustavoLiima Caso queira mudar os nomes curtidas/descurtidas para outros só avisar. Ao meu ver essa era a melhor opção.
